# Generated by Django 5.0.3 on 2024-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('parentCode', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('today_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
